insert into khgl_yhml(yhmc,yhxz) values('北京银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('秦皇岛银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('阳泉市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('鄂尔多斯银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('吉林银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('抚顺银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('铁岭银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('上海银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('温州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江泰隆商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('江西银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('青岛银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('威海市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('宁波通商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('郑州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('平顶山市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('广东华兴银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('重庆银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('德阳市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('遂宁市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('玉溪市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('西安市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('石嘴山银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('西藏银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('天津银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('沧州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('长治银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('廊坊银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('盛京银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('丹东银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('朝阳银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('南京银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('嘉兴银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江民泰商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('九江银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('临商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('齐商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('宁波东海银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('中原银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('广东南粤银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('长沙银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('重庆三峡银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('泸州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('雅安市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('曲靖市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('甘肃银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('库尔勒市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('长安银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('河北银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('承德银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('晋城银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('张家口市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('锦州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('营口银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('哈尔滨银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('湖州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江稠州商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('赣州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('枣庄银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('泰安银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('苏州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('洛阳银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('广州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('华融湘江银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('成都银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('乐山市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('贵阳市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('兰州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('乌鲁木齐商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('包商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('邯郸银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('晋中银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('衡水银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('葫芦岛银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('盘锦市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('龙江银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏长江商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('绍兴银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('福建海峡银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('齐鲁银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('东营银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('日照银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('厦门国际银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('焦作中旅银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('东莞银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('柳州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('绵阳市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('南充市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('贵州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('昆仑银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('克拉玛依市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('邢台银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('保定银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('内蒙古银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('大同银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('大连银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('阜新银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('营口沿海银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('杭州银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('金华银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('厦门银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('上饶银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('潍坊银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('莱商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('徽商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('珠海华润银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('广西北部湾银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('自贡市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('宜宾市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('达州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('宁夏银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('新疆汇和银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('唐山银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('晋商银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('乌海银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('鞍山银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('辽阳银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('宁波银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('台州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('泉州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('济宁市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('烟台银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('德州市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('汉口银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('湖北银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('桂林市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('攀枝花市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('凉山州商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('富滇银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('青海银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('哈密市商业银行','城商行');
insert into khgl_yhml(yhmc,yhxz) values('北京农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('沈阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('营口融生农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('大兴安岭农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏高淳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏宜兴农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏宝应农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏金湖农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏赣榆农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏兴化农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏大丰农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏启东农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏紫金农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('吴江农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('丰县农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江温州鹿城农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江永嘉农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江安吉农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江新昌农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江江山农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江舟山普陀农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宜春农商银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广州农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('天津农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('丹东农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('辽东农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('黑河农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏溧水农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏扬中农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏仪征农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏盱眙农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏沭阳农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏泰州农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏阜宁农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏海安农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('无锡农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('昆山农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('杭州联合农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江瓯海农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江苍南农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江德清农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江金华成泰农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江天台农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江南浔农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('吉安农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('佛山顺德农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('天津滨海农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('东港农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('吉林九台农村商业银行股份有限公司','农商行');
insert into khgl_yhml(yhmc,yhxz) values('友谊农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('徐州淮海农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏丹阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏高邮农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏涟水农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏泗洪农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏姜堰农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏建湖农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏海门农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江阴农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('太仓农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江萧山农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江瑞安农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江禾城农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江绍兴瑞丰农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江义乌农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江丽水莲都农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('景德镇农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('赣州农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('东莞农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('沧州融信农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宽甸农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('长春农村商业银行股份有限公司','农商行');
insert into khgl_yhml(yhmc,yhxz) values('上海农商行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏新沂农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏句容农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏扬州农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏淮安农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏泗阳农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏东台农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏盐城黄海农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏如皋农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('常熟农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('靖江农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江杭州余杭农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江温州龙湾农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江嘉善农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江诸暨农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江永康农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江青田农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('新余农商银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('南昌农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('鄂尔多斯农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('凤城农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('青岛农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('深圳农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏邳州农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏镇江农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏江都农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('连云港东方农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏民丰农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏响水农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏如东农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江苏南通农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('张家港农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('江南农村商业银行 ','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江富阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江乐清农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江海宁农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江上虞农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江东阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('浙江舟山定海海洋农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('九江农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('武汉农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('厦门农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('固原市农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('石嘴山农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宁夏吴忠农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宁夏中卫农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宁夏平罗农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('灵武农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('宁夏黄河农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('贵阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('成都农商银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('重庆农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('海口农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西凌云农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西昭平农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西灌阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西龙胜农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西恭城农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西田阳农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西蒙山农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西融安农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西田东农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('广西资源农村商业银行','农商行');
insert into khgl_yhml(yhmc,yhxz) values('河北省农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('东海县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('沛县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('磐安县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('文成县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('常山县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('龙泉市农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('嵊泗县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('福建省农信联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('湖南省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('云南省农村信用社联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('山西省农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('江苏射阳农村商业银行 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('洪泽县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('泰顺县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('洞头县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('开化县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('缙云县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('浙江松阳恒通村镇银行','农信社');
insert into khgl_yhml(yhmc,yhxz) values('江西省农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('广东省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('陕西信合','农信社');
insert into khgl_yhml(yhmc,yhxz) values('内蒙古自治区农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('铜山县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('灌南县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('临安市农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('海盐县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('临海市农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('松阳县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('建德市农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('山东省农村信用社联合社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('海南省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('永宁县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('辽宁省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('徐州市贾汪区农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('浙江省农村信用社联合社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('平阳县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('桐乡市农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('仙居县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('景宁县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('淳安县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('湖北省农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('四川省农村信用联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('石嘴山市惠农区农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('黑龙江省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('滨海县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('衢州市衢江农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('浦江县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('龙游县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('三门县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('岱山县农村信用合作联社 ','农信社');
insert into khgl_yhml(yhmc,yhxz) values('安徽省农村信用社联合社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('广西壮族自治区农村信用联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('贵州省农村信用社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('盐池县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('贺兰县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('泾源县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('彭阳县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('隆德县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('西吉县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('海原县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('中宁县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('红寺堡区农村信用合作社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('青铜峡市农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('同心县农村信用合作联社','农信社');
insert into khgl_yhml(yhmc,yhxz) values('呼和浩特金谷农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江桐庐农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江兰溪农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江台州路桥农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('江苏睢宁农村合作银行 ','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江平湖农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江武义农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江温岭农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('江苏新沂农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('湖州吴兴农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江台州椒江农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江玉环农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('江苏灌云农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江长兴农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江台州黄岩农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('海南白沙农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江绍兴恒信农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江嵊州农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('浙江台州黄岩农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('海口联合农村商业银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('宁波市市区农村信用合作联社','农合社');
insert into khgl_yhml(yhmc,yhxz) values('宁波慈溪农村合作银行','农合社');
insert into khgl_yhml(yhmc,yhxz) values('宁波鄞州农村合作银行','农合社');
	
